version: '3.8'

services:
  game_server:
    build: ./server
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/usr/share/nginx/html:ro
    depends_on:
      - game_server
    restart: always
